### ISSUE TITLE
Get Aurélien Wolz's approval to publish this new plugin based on his own work

### ISSUE THREAD

**Issue by DanielFlaum** [DanielFlaum/grav-plugin-mermaid-diagrams#1]
Hey @Seao, I would like to publish a new plugin based on your Diagrams plugin. This repository is it.

The major change is to remove the Sequence and Flow diagram types, leaving only mermaid.

I have added a Credit section to README.md which gives credit to you. The copyright notice in LICENSE.md will remain untouched.

All I would like now is your blessing to change the authorship information contained in blueprints.yaml and publish the plugin.

Thank you!
Daniel

**Comment by Seao** [comment]
Hey @DanielFlaum,

No problems, everything is good for me. In agreement with the MIT license, you can deal with the project without restrictions as long as it's mentioned somewhere 👍 As you are the author of this new module, you have to be the one mentioned in authorship section of `blueprints.yaml`

**Comment by DanielFlaum** [comment]
Awesome, thanks so much!
